name: deployements-pr-notifier-cronjob

on:
  schedule:
    - cron: '25 12 * * *' # runs at 12:25 UTC/ 14:25 CET everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL}}
          RELEASE_PR_AUTHOR: ${{ secrets.RELEASE_PR_AUTHOR }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        run: python deployments_pr_notifier.py
